"""Tabela Usuario, Empresa, Professor e Admin

Revision ID: 26bbd27ada72
Revises: 
Create Date: 2026-01-27 19:00:34.720500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bbd27ada72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('genero', sa.Enum('FEMININO', 'MASCULINO', 'TRANSGENERO', 'NAOBINARIO', 'OUTRO', name='generos'), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('USUARIO', 'EMPRESA', 'ADMIN', 'PROFESSOR', name='tiposusuario'), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_telefone'), ['telefone'], unique=True)

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=128), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo_usuario = 'PROFESSOR' AND matricula >= 0 AND matricula <= 999999 OR tipo_usuario != 'PROFESSOR' AND matricula IS NULL", name='ck_matricula_range'),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('empresa')
    op.drop_table('admin')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_telefone'))
        batch_op.drop_index(batch_op.f('ix_usuario_nome'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
